### PR TITLE
Added support for indexing documents

### PR DESCRIPTION
**Pull request by JackuB**
I've had trouble indexing collections, as documents behave somewhat differently. This was causing our CI and rake tasks to fail.

---

I'm not Ruby dev, so feel free to comment on improvements.

### CODE REVIEW

**Comment by pixelastic** [comment]
Thanks for the PR, I'll merge it quickly.

I am not familiar with what kind of Documents can be added to a Jekyll site. Would you mind sharing a few example files?

**Comment by JackuB** [comment]
[Collections](http://jekyllrb.com/docs/collections) _(it says experimental, but api is stable for more than year and I haven't seen any changes to them in Jekyll 3.0)_ use [`Jekyll::Document`](http://www.rubydoc.info/github/jekyll/jekyll/Jekyll/Document). They behave bit differently - they don't have `name` method, so check `indexable` fails. And I had to call them from `collections`.

Our `_config.yml` with collections:

``` yaml
# Collections
# See http://jekyllrb.com/docs/collections/
collections:
  tools:
    title: "Apiary Tools"
    url: /tools/
    output: true
    permalink: /tools/:path/
```

**Comment by pixelastic** [comment]
Oh great, that lets you define any kind of arbitrary data. I can see how this can be useful.

I'll have to add tests (like a fixture of an example document) before merging it. If you want to provide them I might merge it faster, otherwise it will have to wait a couple of days.

**Comment by pixelastic** [comment]
I've integrated support for `Jekyll::Document` and made tests a bit more robust (now use a real Jekyll instance instead of mocks) in [b9b16948](https://github.com/algolia/algoliasearch-jekyll/commit/b9b169482816f8178e17f2ae51b76cdcaf0a0738).

Tell me if this works for you and I'll update the gem.

**Comment by JackuB** [comment]
@pixelastic thanks! Works nicely.

**Comment by pixelastic** [comment]
This is pushed as v0.2.3 on rubygems

**Pull request closed without merging**
